stages:
  - build
  - tests
  - deploy

variables:
  PROJECT_NAME: "MBOX"
  PROJECT_KEY: "mbox"
  GIT_SSL_NO_VERIFY: "1"

  BUILD_OPTS: "--batch-mode -DskipTests=true -e"
  TEST_OPTS: "-DskipTests=false -DtestFailureIgnore=false "
  MAVEN_OPTS: "-Xmx2g -Xms1g -Dmaven.repo.local=.m2 -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=INFO"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .m2

build:
  image: $REGISTRY_URL/devops/docker/bo-build:$BUILD_IMAGE_TAG
  stage: build
  interruptible: true
  variables:
    GIT_STRATEGY: clone
  script:
    - useradd user
    - su user -c "mvn clean verify $BUILD_OPTS"
  only:
    - merge_requests
    - development
  tags:
    - gkr


unit tests:
  image: $REGISTRY_URL/devops/docker/bo-build:$BUILD_IMAGE_TAG
  stage: tests
  interruptible: true
  variables:
    GIT_STRATEGY: clone
  script:
    - useradd user
    - su user -c "mvn test $TEST_OPTS"
  only:
    - merge_requests
    - development
  tags:
    - gkr
  artifacts:
    reports:
      junit:
        - target/surefire-reports/TEST-*.xml
        - target/failsafe-reports/TEST-*.xml

deploy:
  image: $REGISTRY_URL/devops/docker/bo-build:$BUILD_IMAGE_TAG
  stage: deploy
  interruptible: true
  variables:
    GIT_STRATEGY: fetch
  script:
    - useradd user
    - su user -c "mvn deploy $BUILD_OPTS"
  only:
    - merge_requests
    - development
  tags:
    - gkr